In [12]:
# Install required libraries
!pip install --upgrade pip
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install xlrd

Requirement already satisfied: pip in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (24.3.1)
Requirement already satisfied: pandas in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (2.1.3)
Requirement already satisfied: matplotlib in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (4.55.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\vinic\anaconda3\envs\dsfs\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [19]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sn

pd.set_option('display.max_columns', None)

<H3> Dicionário das variáveis </H3>  

`LIMT_BAL:`  
    - Valor do crédito concedido (dólar NT): inclui tanto o crédito ao consumidor individual quanto o crédito familiar (complementar) - Limite total de crédito concedido aos cliente.  
`SEX:`  
    - Genero (1 = Homem; 2 = Mulher).  
`EDUCATION:`  
    - Education (1 = graduate school; 2 = university; 3 = high school; 4 = others).  
`MARRIAGE:`  
    - Marital status (1 = married; 2 = single; 3 = others).  
`AGE:`  
    - Age (year).  
`PAY_1 - PAY_6:`  
    - Histórico de pagamentos anteriores. Acompanhamos os registros de pagamentos mensais anteriores (de abril a setembro de 2005) da seguinte forma: X6 = situação de pagamento em setembro de 2005; X7 = situação de reembolso em agosto de 2005; . . .;X11 = situação de reembolso em abril de 2005. A escala de mensuração da situação de reembolso é: -1 = pagar em dia; 1 = atraso de pagamento de um mês; 2 = atraso no pagamento há dois meses; . . .; 8 = atraso no pagamento há oito meses; 9 = atraso no pagamento por nove meses ou mais.  
`BILL_AMT1 - BILL_AMT6:`  
    - Valor do extrato da conta (dólar NT). X12 = valor do extrato da conta em setembro de 2005; X13 = valor do extrato da conta em agosto de 2005; . . .; X17 = valor do extrato da conta em abril de 2005.   
`PAY_AMT1 - PAY_AMT6:`  
    - Valor do pagamento anterior (dólar NT). X18 = valor pago em setembro de 2005; X19 = valor pago em agosto de 2005; . . .;X23 = valor pago em abril de 2005.  


`TARGET - default payment next month:`  
    - Esta pesquisa empregou uma variável binária, pagamento inadimplente (Sim = 1, Não = 0), como variável resposta. Este estudo revisou a literatura e utilizou as seguintes 23 variáveis ​​como variáveis ​​explicativas.

In [20]:
df = pd.read_excel('C:/Users/vinic/Desktop/Data Science/Data-science-projects-with-python/Data/default_of_credit_card_clients__courseware_version_1_21_19.xls')
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [16]:
# Size of the Dataframe
df.shape

(30000, 25)